In [1]:
import pandas as pd
import nltk
import string

In [30]:
df = pd.read_csv("Concat_ML_Data/Election_2008.csv")

In [31]:
# Keeping the tweet columns for both datasets
# df=pd.DataFrame(df, columns=['tweet', 'candidate'])
df.head()

,tweet,replies_count,retweets_count,likes_count,candidate,tweet_length,Subjectivity,Polarity,Sentiment,year
0,Working on public service spots for Barack Oba...,0,0,0,Barack,12,0.533333,0.500000,Positive,2008
1,An lise candidatos precisam de pol tica regula...,0,0,0,Barack,16,0.000000,0.000000,Neutral,2008
2,Barack Obama LIVE Barack and Joe in Fredricksb...,0,0,0,Barack,9,0.500000,0.136364,Positive,2008
3,kid keeps saying interchangeably my name is ba...,0,0,0,Barack,18,0.200000,-0.100000,Negative,2008
4,The media darling Barack Obama,0,0,0,Barack,5,0.000000,0.000000,Neutral,2008

In [32]:
# Creating Function to tokenize words in tweet columns
def tokenized_words(row):
    tweet = row['tweet']
    tokens = nltk.word_tokenize(tweet)
    token_wds = [word for word in tokens if word.isalpha()]
    return token_wds

In [33]:
df['t_words']=df.apply(tokenized_words, axis=1)
df.head()

,tweet,replies_count,retweets_count,likes_count,candidate,tweet_length,Subjectivity,Polarity,Sentiment,year,t_words
0,Working on public service spots for Barack Oba...,0,0,0,Barack,12,0.533333,0.500000,Positive,2008,"[Working, on, public, service, spots, for, Bar..."
1,An lise candidatos precisam de pol tica regula...,0,0,0,Barack,16,0.000000,0.000000,Neutral,2008,"[An, lise, candidatos, precisam, de, pol, tica..."
2,Barack Obama LIVE Barack and Joe in Fredricksb...,0,0,0,Barack,9,0.500000,0.136364,Positive,2008,"[Barack, Obama, LIVE, Barack, and, Joe, in, Fr..."
3,kid keeps saying interchangeably my name is ba...,0,0,0,Barack,18,0.200000,-0.100000,Negative,2008,"[kid, keeps, saying, interchangeably, my, name..."
4,The media darling Barack Obama,0,0,0,Barack,5,0.000000,0.000000,Neutral,2008,"[The, media, darling, Barack, Obama]"

In [34]:
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))

In [35]:
# Creating Function to remove stop words in tweet column
def remove_stop_wds(row):
    t_words=row['t_words']
    meaningful_words = [word for word in t_words if not word in stops]
    return (meaningful_words)

In [36]:
# Applying remove_stop_wds function to dataset
df['final_wds']=df.apply(remove_stop_wds, axis=1)
df.head()

,tweet,replies_count,retweets_count,likes_count,candidate,tweet_length,Subjectivity,Polarity,Sentiment,year,t_words,final_wds
0,Working on public service spots for Barack Oba...,0,0,0,Barack,12,0.533333,0.500000,Positive,2008,"[Working, on, public, service, spots, for, Bar...","[Working, public, service, spots, Barack, Obam..."
1,An lise candidatos precisam de pol tica regula...,0,0,0,Barack,16,0.000000,0.000000,Neutral,2008,"[An, lise, candidatos, precisam, de, pol, tica...","[An, lise, candidatos, precisam, de, pol, tica..."
2,Barack Obama LIVE Barack and Joe in Fredricksb...,0,0,0,Barack,9,0.500000,0.136364,Positive,2008,"[Barack, Obama, LIVE, Barack, and, Joe, in, Fr...","[Barack, Obama, LIVE, Barack, Joe, Fredricksbu..."
3,kid keeps saying interchangeably my name is ba...,0,0,0,Barack,18,0.200000,-0.100000,Negative,2008,"[kid, keeps, saying, interchangeably, my, name...","[kid, keeps, saying, interchangeably, name, ba..."
4,The media darling Barack Obama,0,0,0,Barack,5,0.000000,0.000000,Neutral,2008,"[The, media, darling, Barack, Obama]","[The, media, darling, Barack, Obama]"

In [37]:
df.count()

tweet             5550
replies_count     5550
retweets_count    5550
likes_count       5550
candidate         5550
tweet_length      5550
Subjectivity      5550
Polarity          5550
Sentiment         5550
year              5550
t_words           5550
final_wds         5550
dtype: int64

In [38]:
df.to_csv(r'C:\Users\Greg\Documents\Analysis_Projects\US_Election_NLP\US_Election_NLP\Concat_ML_Data\wordcloud_2008.csv', index = False, header=True)